import React from "react";
import { Document, Page, Text, View } from "@react-pdf/renderer";
import { styles } from "./styles";

interface ChecklistItem {
  field: string;
  label: string;
  required: boolean;
  present: boolean;
}

interface PackSection {
  type: string;
  label: string;
  source: string;
  fieldsProvided: string[];
  data: Record<string, unknown>;
}

interface AuditEvent {
  id: string;
  event_type: string;
  actor_type: string;
  created_at: string;
}

export interface PackPdfData {
  packId: string;
  shopName: string;
  disputeGid: string;
  disputeReason: string | null;
  generatedAt: string;
  completenessScore: number;
  checklist: ChecklistItem[];
  blockers: string[];
  recommendedActions: string[];
  sections: PackSection[];
  auditEvents: AuditEvent[];
}

function formatDate(iso: string | null): string {
  if (!iso) return "—";
  try {
    return new Date(iso).toLocaleString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  } catch {
    return iso;
  }
}

function CoverPage({ data }: { data: PackPdfData }) {
  const scoreColor =
    data.completenessScore >= 80
      ? "#22C55E"
      : data.completenessScore >= 50
        ? "#F59E0B"
        : "#EF4444";

  return (
    <Page size="A4" style={styles.coverPage}>
      <Text style={styles.coverTitle}>DisputeDesk</Text>
      <Text style={styles.coverSubtitle}>Evidence Pack</Text>
      <Text style={styles.coverMeta}>
        Dispute: {data.disputeGid.split("/").pop()}
      </Text>
      <Text style={styles.coverMeta}>
        Reason: {data.disputeReason ?? "Unknown"}
      </Text>
      <Text style={styles.coverMeta}>Shop: {data.shopName}</Text>
      <Text style={styles.coverMeta}>
        Generated: {formatDate(data.generatedAt)}
      </Text>
      <Text style={[styles.coverScore, { color: scoreColor }]}>
        Completeness: {data.completenessScore}%
      </Text>
      {data.blockers.length > 0 && (
        <View style={[styles.blockerBox, { marginTop: 20, maxWidth: 400 }]}>
          <Text style={styles.blockerText}>
            {data.blockers.length} blocker(s): {data.blockers.join(", ")}
          </Text>
        </View>
      )}
      <Text style={[styles.footer, { position: "absolute", bottom: 40 }]}>
        Generated by DisputeDesk — evidence for internal use and dispute
        response.
      </Text>
    </Page>
  );
}

function ChecklistSection({ checklist }: { checklist: ChecklistItem[] }) {
  return (
    <View>
      <Text style={styles.sectionTitle}>Evidence Checklist</Text>
      {checklist.map((item) => (
        <View key={item.field} style={styles.checkItem}>
          <Text style={styles.checkIcon}>{item.present ? "✓" : "✗"}</Text>
          <Text style={styles.checkLabel}>{item.label}</Text>
          {item.required && !item.present && (
            <Text style={styles.checkRequired}>(REQUIRED)</Text>
          )}
        </View>
      ))}
    </View>
  );
}

function OrderSection({ data }: { data: Record<string, unknown> }) {
  const totals = data.totals as Record<string, string> | undefined;
  const lineItems = data.lineItems as
    | Array<{
        title: string;
        variant?: string;
        quantity: number;
        total: string;
        currency: string;
        sku?: string;
      }>
    | undefined;

  return (
    <View>
      <Text style={styles.sectionTitle}>Order Details</Text>
      <View style={styles.kvRow}>
        <Text style={styles.kvLabel}>Order</Text>
        <Text style={styles.kvValue}>{String(data.orderName ?? "—")}</Text>
      </View>
      <View style={styles.kvRow}>
        <Text style={styles.kvLabel}>Created</Text>
        <Text style={styles.kvValue}>{formatDate(data.createdAt as string)}</Text>
      </View>
      <View style={styles.kvRow}>
        <Text style={styles.kvLabel}>Financial Status</Text>
        <Text style={styles.kvValue}>
          {String(data.financialStatus ?? "—")}
        </Text>
      </View>
      <View style={styles.kvRow}>
        <Text style={styles.kvLabel}>Fulfillment Status</Text>
        <Text style={styles.kvValue}>
          {String(data.fulfillmentStatus ?? "—")}
        </Text>
      </View>

      {totals && (
        <View style={{ marginTop: 8 }}>
          <Text style={styles.sectionSubtitle}>Totals</Text>
          {["subtotal", "shipping", "tax", "discounts", "total", "refunded"].map(
            (key) =>
              totals[key] != null && (
                <View key={key} style={styles.kvRow}>
                  <Text style={styles.kvLabel}>
                    {key.charAt(0).toUpperCase() + key.slice(1)}
                  </Text>
                  <Text style={styles.kvValue}>
                    {totals.currency} {totals[key]}
                  </Text>
                </View>
              )
          )}
        </View>
      )}

      {lineItems && lineItems.length > 0 && (
        <View style={{ marginTop: 8 }}>
          <Text style={styles.sectionSubtitle}>Line Items</Text>
          <View style={styles.tableHeader}>
            <Text style={[styles.tableCellBold, { flex: 3 }]}>Item</Text>
            <Text style={styles.tableCellBold}>Qty</Text>
            <Text style={[styles.tableCellBold, { textAlign: "right" }]}>
              Total
            </Text>
          </View>
          {lineItems.map((item, i) => (
            <View key={i} style={styles.tableRow}>
              <Text style={[styles.tableCell, { flex: 3 }]}>
                {item.title}
                {item.variant ? ` (${item.variant})` : ""}
              </Text>
              <Text style={styles.tableCell}>{item.quantity}</Text>
              <Text style={styles.tableCellRight}>
                {item.currency} {item.total}
              </Text>
            </View>
          ))}
        </View>
      )}
    </View>
  );
}

function ShippingSection({ data }: { data: Record<string, unknown> }) {
  const fulfillments = data.fulfillments as
    | Array<{
        fulfillmentId: string;
        status: string;
        displayStatus?: string;
        createdAt: string;
        deliveredAt?: string;
        tracking: Array<{ number?: string; url?: string; carrier?: string }>;
        items: Array<{ title: string; quantity: number }>;
      }>
    | undefined;

  if (!fulfillments?.length) return null;

  return (
    <View>
      <Text style={styles.sectionTitle}>Shipping & Tracking</Text>
      <View style={styles.kvRow}>
        <Text style={styles.kvLabel}>Overall Status</Text>
        <Text style={styles.kvValue}>
          {String(data.overallStatus ?? "—")}
        </Text>
      </View>
      <View style={styles.kvRow}>
        <Text style={styles.kvLabel}>Fulfillments</Text>
        <Text style={styles.kvValue}>{fulfillments.length}</Text>
      </View>

      {fulfillments.map((f, i) => (
        <View key={i} style={{ marginTop: 8 }}>
          <Text style={styles.sectionSubtitle}>
            Fulfillment {i + 1} — {f.displayStatus ?? f.status}
          </Text>
          <View style={styles.kvRow}>
            <Text style={styles.kvLabel}>Shipped</Text>
            <Text style={styles.kvValue}>{formatDate(f.createdAt)}</Text>
          </View>
          {f.deliveredAt && (
            <View style={styles.kvRow}>
              <Text style={styles.kvLabel}>Delivered</Text>
              <Text style={styles.kvValue}>{formatDate(f.deliveredAt)}</Text>
            </View>
          )}
          {f.tracking.map((t, j) => (
            <View key={j} style={styles.kvRow}>
              <Text style={styles.kvLabel}>
                Tracking{f.tracking.length > 1 ? ` ${j + 1}` : ""}
              </Text>
              <Text style={styles.kvValue}>
                {t.carrier ? `${t.carrier}: ` : ""}
                {t.number ?? "—"}
                {t.url ? ` (${t.url})` : ""}
              </Text>
            </View>
          ))}
        </View>
      ))}
    </View>
  );
}

function PolicySection({ data }: { data: Record<string, unknown> }) {
  const policies = data.policies as
    | Array<{
        policyType: string;
        url?: string;
        capturedAt: string;
        textPreview?: string;
        textLength: number;
      }>
    | undefined;

  if (!policies?.length) return null;

  return (
    <View>
      <Text style={styles.sectionTitle}>Store Policies</Text>
      {policies.map((p, i) => (
        <View key={i} style={{ marginBottom: 10 }}>
          <Text style={styles.sectionSubtitle}>
            {p.policyType.charAt(0).toUpperCase() + p.policyType.slice(1)}{" "}
            Policy
          </Text>
          <View style={styles.kvRow}>
            <Text style={styles.kvLabel}>Captured</Text>
            <Text style={styles.kvValue}>{formatDate(p.capturedAt)}</Text>
          </View>
          {p.url && (
            <View style={styles.kvRow}>
              <Text style={styles.kvLabel}>URL</Text>
              <Text style={styles.kvValue}>{p.url}</Text>
            </View>
          )}
          {p.textPreview && (
            <Text style={styles.policyText}>
              {p.textPreview}
              {p.textLength > 500 ? `\n\n... (${p.textLength} chars total)` : ""}
            </Text>
          )}
        </View>
      ))}
    </View>
  );
}

function ManualUploadsSection({ data }: { data: Record<string, unknown> }) {
  const uploads = data.uploads as
    | Array<{ id: string; label: string; type: string; createdAt: string }>
    | undefined;

  if (!uploads?.length) return null;

  return (
    <View>
      <Text style={styles.sectionTitle}>Manual Attachments</Text>
      <View style={styles.tableHeader}>
        <Text style={[styles.tableCellBold, { flex: 3 }]}>File</Text>
        <Text style={styles.tableCellBold}>Type</Text>
        <Text style={styles.tableCellBold}>Uploaded</Text>
      </View>
      {uploads.map((u, i) => (
        <View key={i} style={styles.tableRow}>
          <Text style={[styles.tableCell, { flex: 3 }]}>{u.label}</Text>
          <Text style={styles.tableCell}>{u.type}</Text>
          <Text style={styles.tableCell}>{formatDate(u.createdAt)}</Text>
        </View>
      ))}
    </View>
  );
}

function AuditSection({ events }: { events: AuditEvent[] }) {
  if (!events.length) return null;

  return (
    <View>
      <Text style={styles.sectionTitle}>Audit Trail</Text>
      {events.map((evt) => (
        <View key={evt.id} style={styles.auditRow}>
          <Text style={styles.auditTime}>{formatDate(evt.created_at)}</Text>
          <Text style={styles.auditEvent}>
            {evt.event_type.replace(/_/g, " ")} ({evt.actor_type})
          </Text>
        </View>
      ))}
    </View>
  );
}

function ContentPage({ data }: { data: PackPdfData }) {
  const orderSections = data.sections.filter(
    (s) => s.source === "shopify_order"
  );
  const shippingSections = data.sections.filter(
    (s) => s.source === "shopify_fulfillments"
  );
  const policySections = data.sections.filter(
    (s) => s.source === "policy_snapshots"
  );
  const manualSections = data.sections.filter(
    (s) => s.source === "manual_upload"
  );

  return (
    <Page size="A4" style={styles.page}>
      <ChecklistSection checklist={data.checklist} />

      {data.blockers.length > 0 && (
        <View style={styles.blockerBox}>
          <Text style={styles.blockerText}>
            Blockers: {data.blockers.join(", ")}
          </Text>
        </View>
      )}
      {data.recommendedActions.length > 0 && (
        <View style={styles.warningBox}>
          <Text style={styles.warningText}>
            Recommended: {data.recommendedActions.join(", ")}
          </Text>
        </View>
      )}

      {orderSections.map((s, i) => (
        <OrderSection key={i} data={s.data} />
      ))}

      {shippingSections.map((s, i) => (
        <ShippingSection key={i} data={s.data} />
      ))}

      {policySections.map((s, i) => (
        <PolicySection key={i} data={s.data} />
      ))}

      {manualSections.map((s, i) => (
        <ManualUploadsSection key={i} data={s.data} />
      ))}

      <AuditSection events={data.auditEvents} />

      <Text style={styles.footer} fixed>
        Generated by DisputeDesk — evidence for internal use and dispute
        response. Pack {data.packId.slice(0, 8)} ·{" "}
        {formatDate(data.generatedAt)}
      </Text>
    </Page>
  );
}

export function EvidencePackDocument({ data }: { data: PackPdfData }) {
  return (
    <Document
      title={`Evidence Pack — ${data.disputeGid.split("/").pop()}`}
      author="DisputeDesk"
      subject="Chargeback Evidence"
    >
      <CoverPage data={data} />
      <ContentPage data={data} />
    </Document>
  );
}
